name: PermGuard
version: '${version}'
main: uz.alex2276564.permguard.PermGuard
api-version: '1.16'
authors: [alex2276564]
description: A Minecraft plugin designed to enhance server security by temporarily revoking admin permissions upon joining and sending security alerts to Telegram. It helps prevent unauthorized access and potential security breaches, ensuring that only authorized personnel can grant elevated privileges.
website: https://github.com/alex2276564/PermGuard
commands:
  permguard:
    description: Main command for PermGuard plugin
    usage: /permguard <reload>
    aliases: [pg]
    permission: permguard.command
permissions:
  permguard.command:
    description: Allows access to basic PermGuard commands
    default: op
  permguard.reload:
    description: Allows reloading the PermGuard configuration
    default: op