name: PermGuard
version: '${version}'
main: uz.alex2276564.permguard.PermGuard
api-version: '1.16'
authors: [alex2276564]
description: A Minecraft plugin designed to enhance server security by temporarily revoking admin permissions upon joining. It helps prevent unauthorized access and potential security breaches, ensuring that only authorized personnel can grant elevated privileges.
commands:
  permguardreload:
    description: Reload PermGuard configuration
    usage: /permguardreload
    permission: permguard.reload
website: https://github.com/alex2276564/PermGuard