blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/alex2276564/PermGuard#readme
    about: Check out the documentation for installation and security configuration

  - name: Security Standards
    url: https://www.iso.org/isoiec-27001-information-security.html
    about: Learn more about ISO/IEC 27001 security standards

  - name: CIS Controls
    url: https://www.cisecurity.org/controls
    about: Learn more about CIS Controls