name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  dependency-review:
    name: 🧩 Dependency Review
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@main

      - name: Dependency Review
        uses: actions/dependency-review-action@main
        with:
          fail-on-severity: high
